# Generated by Django 3.0.8 on 2020-07-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.TextField(blank=True, default=None, null=True, verbose_name='Device Type')),
                ('hostname', models.TextField(blank=True, default=None, verbose_name='Hostname')),
                ('ip_address', models.TextField(blank=True, default=None, verbose_name='IP Address')),
                ('mac_vendor', models.TextField(blank=True, default=None, null=True, verbose_name='MAC Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.TextField(blank=True, default=None, null=True, verbose_name='Device Type')),
                ('number_of_devices', models.IntegerField(default=1, verbose_name='Number Of Devices')),
            ],
        ),
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField(blank=True, default=None, verbose_name='Hostname')),
                ('ip_address', models.TextField(blank=True, default=None, verbose_name='IP Address')),
                ('port_number', models.IntegerField(default=0, null=True, verbose_name='Port Number')),
                ('protocol_type', models.TextField(blank=True, default=None, verbose_name='Protocol Type (TCP/UDP)')),
                ('device_state', models.TextField(blank=True, default=None, verbose_name='Device State')),
                ('device_service', models.TextField(blank=True, default=None, verbose_name='Device Service')),
                ('device_version', models.TextField(blank=True, default=None, verbose_name='Device Version')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_problem', models.TextField(default=None, verbose_name='Device Problem')),
                ('problem_severity', models.IntegerField(default=0, verbose_name='Problem Severity')),
                ('device', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.NetworkDevices', verbose_name='Devices')),
            ],
        ),
    ]
