# Generated by Django 3.0.8 on 2020-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_networkdevices_device_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevices',
            name='connects_to',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Connects To'),
        ),
    ]
